--https://www.postgresql.org/docs/15/datatype.html
CREATE TABLE IF NOT EXISTS device_event (
    event_id UUID PRIMARY KEY,
    adverse_event_flag TEXT,
    date_facility_aware DATE,
    date_manufacturer_received DATE,
    date_of_event DATE,
    date_received DATE,
    date_report DATE,
    date_report_to_fda DATE,
    date_report_to_manufacturer DATE,
    device_date_of_manufacturer DATE,
    distributor_address_1 TEXT,
    distributor_address_2 TEXT,
    distributor_city TEXT,
    distributor_name TEXT,
    distributor_state TEXT,
    distributor_zip_code TEXT,
    distributor_zip_code_ext TEXT,
    event_key TEXT,
    event_location TEXT,
    event_type TEXT,
    expiration_date_of_device DATE,
    health_professional TEXT,
    initial_report_to_fda TEXT,
    manufacturer_address_1 TEXT,
    manufacturer_address_2 TEXT,
    manufacturer_city TEXT,
    manufacturer_contact_address_1 TEXT,
    manufacturer_contact_address_2 TEXT,
    manufacturer_contact_area_code TEXT,
    manufacturer_contact_city TEXT,
    manufacturer_contact_country TEXT,
    manufacturer_contact_exchange TEXT,
    manufacturer_contact_extension TEXT,
    manufacturer_contact_f_name TEXT,
    manufacturer_contact_l_name TEXT,
    manufacturer_contact_pcity TEXT,
    manufacturer_contact_pcountry TEXT,
    manufacturer_contact_phone_number TEXT,
    manufacturer_contact_plocal TEXT,
    manufacturer_contact_postal_code TEXT,
    manufacturer_contact_state TEXT,
    manufacturer_contact_t_name TEXT,
    manufacturer_contact_zip_code TEXT,
    manufacturer_contact_zip_ext TEXT,
    manufacturer_country TEXT,
    manufacturer_g1_address_1 TEXT,
    manufacturer_g1_address_2 TEXT,
    manufacturer_g1_city TEXT,
    manufacturer_g1_country TEXT,
    manufacturer_g1_name TEXT,
    manufacturer_g1_postal_code TEXT,
    manufacturer_g1_state TEXT,
    manufacturer_g1_zip_code TEXT,
    manufacturer_g1_zip_code_ext TEXT,
    manufacturer_link_flag TEXT,
    manufacturer_name TEXT,
    manufacturer_postal_code TEXT,
    manufacturer_state TEXT,
    manufacturer_zip_code TEXT,
    manufacturer_zip_code_ext TEXT,
    mdr_report_key TEXT UNIQUE,
    number_devices_in_event TEXT,
    number_patients_in_event TEXT,
    previous_use_code TEXT,
    product_problems TEXT [],
    -- Array to store multiple product problems
    product_problem_flag TEXT,
    remedial_action TEXT [],
    -- Array with defined values
    removal_correction_number TEXT,
    report_date DATE,
    report_number TEXT,
    report_source_code TEXT,
    report_to_fda TEXT,
    report_to_manufacturer TEXT,
    reporter_occupation_code TEXT,
    reprocessed_and_reused_flag TEXT,
    single_use_flag TEXT,
    source_type TEXT [],
    type_of_report TEXT [] 
);