CREATE TABLE IF NOT EXISTS device (
    event_id UUID REFERENCES device_event(event_id) ON DELETE CASCADE,
    brand_name TEXT,
    catalog_number TEXT,
    date_received DATE,
    date_removed_flag TEXT,
    date_returned_to_manufacturer DATE,
    device_age_text TEXT,
    device_availability TEXT,
    device_evaluated_by_manufacturer TEXT,
    device_event_key TEXT,
    device_operator TEXT,
    device_report_product_code TEXT,
    device_sequence_number TEXT,
    expiration_date_of_device DATE,
    generic_name TEXT,
    udi_di TEXT,
    implant_flag TEXT,
    lot_number TEXT,
    manufacturer_d_address_1 TEXT,
    manufacturer_d_address_2 TEXT,
    manufacturer_d_city TEXT,
    manufacturer_d_country TEXT,
    manufacturer_d_name TEXT,
    manufacturer_d_postal_code TEXT,
    manufacturer_d_state TEXT,
    manufacturer_d_zip_code TEXT,
    manufacturer_d_zip_code_ext TEXT,
    model_number TEXT,
    other_id_number TEXT,
    udi_public TEXT,
    openfda_device_name TEXT,
    openfda_medical_specialty_description TEXT,
    openfda_regulation_number TEXT,
    openfda_device_class TEXT
);
