CREATE TABLE pma_submission (
    id UUID PRIMARY KEY,
    advisory_committee_code CHAR(2),
    advisory_committee_description TEXT,
    ao_statement TEXT,
    applicant TEXT,
    city TEXT,
    state TEXT,
    street_1 TEXT,
    street_2 TEXT,
    zip VARCHAR(10),
    zip_ext VARCHAR(10),
    date_received DATE,
    decision_code CHAR(4),
    decision_date DATE,
    docket_number TEXT,
    expedited_review_flag CHAR(1),
    fed_reg_notice_date DATE,
    generic_name TEXT,
    pma_number TEXT,
    product_code VARCHAR(10),
    supplement_number TEXT,
    supplement_reason TEXT,
    supplement_type TEXT,
    trade_name TEXT,
    openfda_device_class CHAR(1),
    openfda_device_name TEXT,
    openfda_medical_specialty_description TEXT,
    openfda_regulation_number TEXT,
    openfda_fei_number TEXT[],
    openfda_registration_number TEXT[]
);