services:
  server:
    image: datagnomesteam/project_server:latest
    container_name: data_server
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000" # FastAPI
      - "8501:8501" # Streamlit
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=datastore
      - DB_USER=chris
      - DB_PASSWORD=chris
      - API_URL=http://server:8000
    #Uncomment for debugging later
    #volumes:
    #  - ./server:/app
    networks:
      - app_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U server -d datastore"]
      interval: 5s
      timeout: 5s
      retries: 5


  db:
    image: datagnomesteam/project_database:latest
    container_name: db
    shm_size: "2gb"
    deploy:
      resources:
        limits:
          memory: 6G
        reservations:
          memory: 4G
    ports:
      - "5432:5432"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=datastore
      - DB_USER=chris
      - DB_PASSWORD=chris
      - MEMORY_LIMIT=4G
    networks:
      - app_network
    restart: unless-stopped


networks:
  app_network:
    driver: bridge