name: Push Database To Dockerhub

on:
  push:
    branches:
      - main
      - docker-*
    paths:
      - 'db/**'
      - '!db/Dockerfile.local'
      - '.github/workflows/PushDatabase.yml'
  workflow_dispatch:

jobs:
  build-and-push:
    timeout-minutes: 60
    runs-on: ubuntu-22.04
    env:
      DOCKERHUB_USERNAME: datagnomesteam
      MAIN_REPO_NAME: datagnomesteam/project_database
      DOCKERFILE_PATH: ${{ github.workspace }}/db
      PLATFORM: ${{ matrix.platform }}
      DOCKER_BUILDKIT: 1
      #BUILDKIT_INLINE_CACHE: 1
      ACTIONS_STEP_DEBUG: true
      ACTIONS_RUNNER_DEBUG: true

    strategy:
      matrix:
        platform: [linux/amd64, linux/arm64]

    steps:
      - name: Check initial disk space
        run: df -h

      - name: Maximize build space
        run: |
          echo "Removing large packages to maximize disk space..."
          sudo rm -rf /usr/share/dotnet /opt/ghc /usr/local/lib/android /usr/lib/jvm || true
          sudo rm -rf /usr/local/share/boost /usr/share/swift /usr/local/.ghcup || true
          sudo docker image prune --all --force || true
          sudo apt-get purge -y '^ghc-.*' '^dotnet-.*' '^aspnetcore-.*' '^mysql-.*' '^php.*' azure-cli google-cloud-cli hhvm google-chrome-stable firefox powershell mono-devel libgl1-mesa-dri || true
          sudo apt-get autoremove -y || true
          sudo apt-get clean || true
          echo "Disk space after cleanup:"
          df -h

      - name: Install essential packages
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            ca-certificates \
            curl \
            gnupg \
            lsb-release \
            jq \
            gzip \
            tar \
            qemu-user-static

      - name: Install Docker
        run: |
          sudo mkdir -p /etc/apt/keyrings
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
          echo \
            "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
            $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends docker-ce docker-ce-cli containerd.io docker-compose-plugin

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: ${{ env.PLATFORM }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: |
            network=host
            image=moby/buildkit:master
            memory=6g

      - name: Retrieve Docker Credentials
        id: retrieve-credentials
        run: |
          echo "Retrieving Docker credentials..."
          echo "${{ secrets.DOCKERHUB_TOKEN }}" > docker-credentials.txt
          chmod 600 docker-credentials.txt

      - name: Log in to Docker Hub
        run: |
          echo "Logging in to Docker Hub..."
          docker_username=${{ env.DOCKERHUB_USERNAME }}
          docker_password=$(cat docker-credentials.txt)
          echo "::add-mask::$docker_password"
          echo "$docker_password" | sudo docker login -u "$docker_username" --password-stdin

      - name: Clean up old Docker images on Docker Hub
        run: |
          echo "Attempting to remove 'latest' tag from Docker Hub..."
          TOKEN=$(curl -s -H "Content-Type: application/json" -X POST -d "{\"username\": \"${{ env.DOCKERHUB_USERNAME }}\", \"password\": \"$(cat docker-credentials.txt)\"}" https://hub.docker.com/v2/users/login/ | jq -r .token)
          if [ -z "$TOKEN" ] || [ "$TOKEN" == "null" ]; then
            echo "Failed to get Docker Hub token."
          else
            DELETE_STATUS_CODE=$(curl -s -o /dev/null -w "%{http_code}" -X DELETE -H "Authorization: JWT ${TOKEN}" "https://hub.docker.com/v2/repositories/${{ env.MAIN_REPO_NAME }}/tags/latest/")
            echo "Delete request for 'latest' tag sent. Status code: $DELETE_STATUS_CODE"
            if [ "$DELETE_STATUS_CODE" -ne 204 ] && [ "$DELETE_STATUS_CODE" -ne 404 ]; then
              echo "Warning: Failed to delete 'latest' tag (Status: $DELETE_STATUS_CODE). It might not exist or there was an error."
            fi
          fi

      - name: Build and push final image
        uses: docker/build-push-action@v6
        with:
          context: ${{ env.DOCKERFILE_PATH }}
          file: ${{ env.DOCKERFILE_PATH }}/Dockerfile.hub
          platforms: ${{ env.PLATFORM }}
          push: true
          tags: ${{ env.MAIN_REPO_NAME }}:latest
          outputs: type=image,compression=zstd,compression-level=19
          provenance: false
          secrets: |
            dataset_url=${{ secrets.DATASET_URL_SLIM }}

      - name: Update repo description
        if: matrix.platform == 'linux/amd64'
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          token: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: ${{ env.MAIN_REPO_NAME }}
          readme-filepath: ./README.md

      - name: Cleanups
        if: always()
        run: |
          if [ -f docker-credentials.txt ]; then
            rm -f docker-credentials.txt
          fi
          sudo docker system prune -af --volumes || true
          sudo docker builder prune -af || true
          sudo docker image prune -af || true
          echo "Final disk space:"
          df -h