name: Push Database To Dockerhub (Local)

on:
  workflow_dispatch:

jobs:
  prepare-database:
    timeout-minutes: 120
    runs-on: ubuntu-latest
    env:
      DOCKERHUB_USERNAME: datagnomesteam
      MAIN_REPO_NAME: datagnomesteam/project_database
      DOCKERFILE_PATH: ${{ github.workspace }}/db
      DOCKER_BUILDKIT: 1
      BUILDKIT_INLINE_CACHE: 1
      ACT: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: |
            network=host
            image=moby/buildkit:master

      - name: Retrieve Docker Credentials
        id: retrieve-credentials
        run: |
          echo "Retrieving Docker credentials..."
          echo "${{ secrets.DOCKERHUB_TOKEN }}" > docker-credentials.txt
          chmod 600 docker-credentials.txt

      - name: Log in to Docker Hub
        run: |
          echo "Logging in to Docker Hub..."
          docker_username=${{ env.DOCKERHUB_USERNAME }}
          docker_password=$(cat docker-credentials.txt)
          echo "::add-mask::$docker_password"
          echo "$docker_password" | docker login -u "$docker_username" --password-stdin

      - name: Download and prepare database
        uses: docker/build-push-action@v6
        with:
          context: ${{ env.DOCKERFILE_PATH }}
          file: ${{ env.DOCKERFILE_PATH }}/Dockerfile.hub
          target: prepare
          push: false
          load: true
          tags: ${{ env.MAIN_REPO_NAME }}:prepare
          secrets: |
            dataset_url=${{ secrets.DATASET_URL }}
          build-args: |
            MEMORY_LIMIT=6G
          cache-from: type=registry,ref=${{ env.MAIN_REPO_NAME }}:prepare-cache
          cache-to: type=registry,ref=${{ env.MAIN_REPO_NAME }}:prepare-cache,mode=max

      - name: Save prepared database
        run: |
          docker save ${{ env.MAIN_REPO_NAME }}:prepare | gzip > prepared_db.tar.gz
          docker system prune -af --volumes || true

      - name: Cache prepared database
        uses: actions/cache@v4
        with:
          path: prepared_db.tar.gz
          key: prepared-db-${{ github.run_id }}
          restore-keys: |
            prepared-db-

      - name: Cleanups
        if: always()
        run: |
          if [ -f docker-credentials.txt ]; then
            rm -f docker-credentials.txt
          fi
          if [ -f prepared_db.tar.gz ]; then
            rm -f prepared_db.tar.gz
          fi
          docker system prune -af --volumes || true
          docker builder prune -af || true
          docker image prune -af || true

  build-and-push:
    needs: prepare-database
    timeout-minutes: 60
    runs-on: ubuntu-latest
    env:
      DOCKERHUB_USERNAME: datagnomesteam
      MAIN_REPO_NAME: datagnomesteam/project_database
      DOCKERFILE_PATH: ${{ github.workspace }}/db
      PLATFORM: ${{ matrix.platform }}
      DOCKER_BUILDKIT: 1
      BUILDKIT_INLINE_CACHE: 1
      ACT: true

    strategy:
      matrix:
        platform: [linux/amd64]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: ${{ env.PLATFORM }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: |
            network=host
            image=moby/buildkit:master

      - name: Restore prepared database
        uses: actions/cache@v4
        with:
          path: prepared_db.tar.gz
          key: prepared-db-${{ needs.prepare-database.outputs.run_id }}

      - name: Load prepared database
        run: |
          gunzip -c prepared_db.tar.gz | docker load

      - name: Retrieve Docker Credentials
        id: retrieve-credentials
        run: |
          echo "Retrieving Docker credentials..."
          echo "${{ secrets.DOCKERHUB_TOKEN }}" > docker-credentials.txt
          chmod 600 docker-credentials.txt

      - name: Log in to Docker Hub
        run: |
          echo "Logging in to Docker Hub..."
          docker_username=${{ env.DOCKERHUB_USERNAME }}
          docker_password=$(cat docker-credentials.txt)
          echo "::add-mask::$docker_password"
          echo "$docker_password" | docker login -u "$docker_username" --password-stdin

      - name: Clean up old Docker images
        run: |
          TOKEN=$(curl -s -H "Content-Type: application/json" -X POST -d "{\"username\": \"${{ env.DOCKERHUB_USERNAME }}\", \"password\": \"$(cat docker-credentials.txt)\"}" https://hub.docker.com/v2/users/login/ | jq -r .token)
          curl -s -X DELETE -H "Authorization: JWT ${TOKEN}" "https://hub.docker.com/v2/repositories/${{ env.MAIN_REPO_NAME }}/tags/latest/"

      - name: Build and push final image
        uses: docker/build-push-action@v6
        with:
          context: ${{ env.DOCKERFILE_PATH }}
          file: ${{ env.DOCKERFILE_PATH }}/Dockerfile.hub
          platforms: ${{ env.PLATFORM }}
          push: true
          tags: ${{ env.MAIN_REPO_NAME }}:latest
          outputs: type=image,compression=zstd,compression-level=19
          cache-from: type=registry,ref=${{ env.MAIN_REPO_NAME }}:buildcache
          cache-to: type=registry,ref=${{ env.MAIN_REPO_NAME }}:buildcache,mode=max

      - name: Update repo description
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_PASSWORD }}
          repository: ${{ env.MAIN_REPO_NAME }}
          readme-filepath: ./README.md

      - name: Cleanups
        if: always()
        run: |
          if [ -f docker-credentials.txt ]; then
            rm -f docker-credentials.txt
          fi
          if [ -f prepared_db.tar.gz ]; then
            rm -f prepared_db.tar.gz
          fi
          docker system prune -af --volumes || true
          docker builder prune -af || true
          docker image prune -af || true 